title: Sander van Veldhuizen
email: your-email@example.com
description: >-
  Personal site with an introduction and a list of congresses I've attended.
baseurl: ""
url: "https://sander-van-veldhuizen.github.io"
theme: minima
